train:

  data_loader:
    batch_size: 64
    image:
      enabled: True
      data_path: "/home/sv/Downloads/tiny_imagenet/val/images"
      annotation_file: "/home/sv/Downloads/tiny_imagenet/val/val_annotations.txt"
      annotation_map_file: "/home/sv/Downloads/archive/tiny-imagenet-200/wnids.txt"
      preprocess: True
      train_split: 0.7
      val_split: 0.2
      test_split: 0.1
    text:
      enabled: False
      data_path: ''

  epochs: 1

  device: 'cuda:0'

  optimizer:
    Adam: 
      enabled: True
      lr: 3e-4
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-08
      amsgrad: False
    
    AdamW: 
      enabled: False
      lr: 3e-4

    SGD:
      enabled: False
      lr: 0.001


  learning_rate:
    lr: 0.001
    decaying: True

  model_saver: 
    path: "/home/sv/Documents/models"
    name: 'cifar-10'

  task:
    classification:
      enabled: True
      Image:
        enabled: True
        model:
          name: 'CNNClassifier'
          input_size: [32, 32]
          in_channels: 3
          conv_channel_dims: [512, 512]
          conv_kernel_dims: [3, 3]
          out_dim: 200
        loss:
          name: 'CrossEntropyLoss' # if any parameters for loss, add args here.
          label_smoothing: 0.1
        
      Text:
        enabled: False
        model: 
          name: 'Transformer'
          input_size:
          context_length:
          num_heads:
        loss:
          name: 'HingeEmbeddingLoss'

    object_detection:
      enabled: False
      model: 
        name: 'YOLO'

    image_segmentation:
      enabled: False
      model: 
        name: ''


test:
  batch_size: 8
  data_loader:

  
