train:

  data_loader:
    batch_size: 8
    image:
      enabled: True
      data_path: "/home/sv/Downloads/tiny_imagenet/val/images"
      annotation_file: "/home/sv/Downloads/tiny_imagenet/val/val_annotations.txt"
      annotation_map_file: "/home/sv/Downloads/archive/tiny-imagenet-200/wnids.txt"
      preprocess: True
      train_split: 0.7
      val_split: 0.2
      test_split: 0.1
    text:
      enabled: False
      data_path: ''

  epochs: 100

  device: 'cuda:0'

  optimizer:
    Adam: True
    SGD: False

  learning_rate:
    lr: 0.001
    decaying: True

  model_saver: 
    path: "/home/sv/Documents/models"
    name: 'cifar-10'

  task:
    classification:
      enabled: True
      Image:
        enabled: True
        model: 
          name: 'CNN'
          in_channels:
          out_channels:
        
      Text:
        enabled: False
        model: 
          name: 'Transformer'

    object_detection:
      enabled: False
      model: 
        name: 'YOLO'

    image_segmentation:
      enabled: False
      model: 
        name: ''


test:
  batch_size: 8
  data_loader:

  
