train:

  data_path: "/home/sv/Documents/"
  epochs: 100

  batch_size: 8

  device: 'cuda:0'

  optimizer:
    Adam: True
    SGD: False

  learning_rate:
    lr: 0.001
    decaying: True

  model_saver: 
    path: "/home/sv/Documents/models"
    name: 'cifar-10'
  task:
    classification:
      
      Image:
        enabled: True
        model: 'CNN'
        
      Text:
        enabled: False
        model: 'Transformer'

    object_detection:
      model: 'YOLO'

    image_segmentation:
      model: ''


test:
  batch_size: 8
